### ISSUE TITLE
Unable to forward-type negative value

### ISSUE THREAD

**Issue by zssarkany** [coders-tm/vue-number-format#10]
First of all: I really appreciate your efforts! This component is great!

When user starts to type a negative value, the typing starts with a - sign naturally.
I checked it on playground, and the negative sign does not appear.
If there are digits already, and user press -, the value becomes negative.
Btw the negative sign appears before the prefix, which seems to be incorrect.

What do you think about this?
(it would be great to have correct behavior in v2.x version, because I use the component in a legacy v2 environment. :(

**Comment by dipaksarkar** [comment]
@zssarkany Thanks for your suggestions. I will change the `minus sign` position.

**Comment by zssarkany** [comment]
Thanks for the feedback :)
