### ISSUE TITLE
max and min don't work in vue2 version(@coders-tm/vue-number-format@2.0.7).

### ISSUE THREAD

**Issue by guohuijiedesu** [coders-tm/vue-number-format#15]

**Comment by guohuijiedesu** [comment]
unable in playground too.

**Comment by dipaksarkar** [comment]
Playground is build on Vue 3 it’s working fine. Please post your code.

**Comment by guohuijiedesu** [comment]
> Playground is build on Vue 3 it’s working fine. Please post your code.

![image](https://user-images.githubusercontent.com/68212601/177681782-dde5f18d-e0dc-45c8-8c8a-294694055f76.png)

**Comment by dipaksarkar** [comment]
Check the docs now, I have updated it.
