### ISSUE TITLE
Is it possible to get the updated value on every keystroke rather than when a change event is emitted?

### ISSUE THREAD

**Issue by martinnobis** [coders-tm/vue-number-format#22]
The v-model variable is currently only updated when the change event occurs, but would it instead be possible to update at each keystroke? e.g. in the playground you can see that the new value only gets updated when the focus disappears from the input. Can we update it at each keystroke instead? Thanks.

**Comment by dipaksarkar** [comment]
Yes, You can use `@input:model-value` event for `Vue 3.0` and `@input` for Vue 2.0

Example for `Vue 3.0` (where make sure that you using `@coders-tm/vue-number-format` latest version)

```html
<template>
  <div><VueNumberFormat :model-value="price" @input:model-value="(val) => (price = val)" v-bind="number"></VueNumberFormat> {{price}}</div>
</template>

<script>
  import { number as VueNumberFormat } from '@coders-tm/vue-number-format'

  export default {
    components: {
      VueNumberFormat,
    },

    data() {
      return {
        price: 123.45,
        number: {
          decimal: '.',
          separator: ',',
          prefix: '$ ',
          precision: 2,
          masked: false,
        },
      }
    },
  }
</script>
```
