### ISSUE TITLE
prefix and suffix props seem to be applied globally

### ISSUE THREAD

**Issue by martinnobis** [coders-tm/vue-number-format#23]
Adding a prefix or suffix prop to one ```<number>``` component applies it to all of them.

```js
<script setup>
import {ref} from 'vue'
import { number } from '@coders-tm/vue-number-format';

const count = ref(5)
const count2 = ref(3)
</script>

<template>
  <number prefix="$" v-model="count" />
  <number v-model="count2" />
</template>
```
<img width="560" alt="Screen Shot 2022-08-11 at 9 34 46 pm" src="https://user-images.githubusercontent.com/6426031/184124780-aff371bf-01da-4b89-9bcc-c8fb1d06cc0f.png">

Here I'd expect that the prefix would only appear on the first component only.

**Comment by dipaksarkar** [comment]
@martinnobis Please use latest version. I have fix it. Thanks for finding the issue. :)

**Comment by martinnobis** [comment]
Thanks, that fixed it!
