### ISSUE TITLE
Only add decimal doesn't update value

### ISSUE THREAD

**Issue by hugo33480** [coders-tm/vue-number-format#24]
Hello, im working on application with prefilled value input and i met this problem:

It seems like add only a decimal does not trigger change event 

exemple:

![Capture d’écran de 2022-08-18 09-33-27](https://user-images.githubusercontent.com/77515560/185336812-5f2f12cb-9e40-4d6e-953b-8090b9fcb105.png)

I have 33, i want 3.3 by just adding a dot

![Capture d’écran de 2022-08-18 09-34-41](https://user-images.githubusercontent.com/77515560/185337055-8ec1be42-c647-451d-9214-67bf32b2b636.png)

and this is not updating

**Comment by dipaksarkar** [comment]
@hugo33480 Please use latest version

**Comment by hugo33480** [comment]
Hello,
Is it possible to fix for Vue 2?

**Comment by dipaksarkar** [comment]
> Hello, Is it possible to fix for Vue 2? @dipaksarkar

@hugo33480 I have published new version for Vue2.0 please install @coders-tm/vue-number-format@2.2.11
