### ISSUE TITLE
Passing modelValue 0 returns null value instead of 0

### ISSUE THREAD

**Issue by Germain-condo-group** [coders-tm/vue-number-format#25]
Scenario:
Passing 0  modelValue in input field
Expected Result: `0` is emitted by ` @input:model-value`
Actual Result: `null` is emitted by ` @input:model-value`

https://github.com/coders-tm/vue-number-format/blob/c06a626fefa70c2dd4d3be39436bcfa743b41a8a/src/number-format.js#L123

I think this check should be changed to not be falsy when input is 0, so it would do expected behaviour.

**Comment by dipaksarkar** [comment]
@Germain-condo-group New version has been released to fix this issue. Please use latest version(v3.1.6) it will fix the issue.

**Comment by Germain-condo-group** [comment]
Thank you for the fix @dipaksarkar !
