### ISSUE TITLE
Null value results in error: string is null

### ISSUE THREAD

**Issue by ww99w** [coders-tm/vue-number-format#26]
When the model value is null, it results in an uncaught error
![image](https://user-images.githubusercontent.com/8907675/192228732-2f3776f7-2edb-4eba-aefd-8c0d0776343e.png)

C# doesn't accept empty string for Decimal? (nullable decimal). I guess I could manually change to empty string when receiving the data and changing back to Null before sending it

**Comment by dipaksarkar** [comment]
I have merged your pr
