### ISSUE TITLE
Issue with dot . in prefix and . for decimal

### ISSUE THREAD

**Issue by rick20** [coders-tm/vue-number-format#32]
This issue happens both in vue 2 and 3.
Currency in our country is prefixed with 'Rp. '  (e.g: Rp. 100,000.00).
To represent this format, I set "Rp. " as the prefix.
For vue 3 version, the issue can be reproduced in the playground by entering "Rp. " as prefix and type in any value, and the browser is crashed.
Is there any workaround for this issue?

**Comment by dipaksarkar** [comment]
@rick20 Please check latest version for vue3
