### ISSUE TITLE
I cant disable negative

### ISSUE THREAD

**Issue by lexar19** [coders-tm/vue-number-format#35]
Hello, this a great component. I currently using this in my project, hopefully you can add disable negative in the near future, thank you.

**Comment by dipaksarkar** [comment]
Please use latest version. I have fix it.

**Comment by dipaksarkar** [comment]
Please use latest version and add `min: 0` to config. I have fix it.

**Comment by lexar19** [comment]
thank you, but sorry forgot to mention that I use the version @coders-tm/vue-number-format@2.2.12 for vue 2

**Comment by dipaksarkar** [comment]
@lexar19  Please use v2.5.0 I have fix it.

**Comment by dipaksarkar** [comment]
@lexar19 Please use v2.6.0

**Comment by thelittlelows** [comment]
@dipaksarkar issue is still present in v2.6.0
https://codesandbox.io/s/vue-2-playground-forked-ycf0i4?file=/src/App.vue
