### ISSUE TITLE
Mobile keyboard type

### ISSUE THREAD

**Issue by isgleb** [coders-tm/vue-number-format#38]
version:  "3.3.1"
Tested with simulator (https://www.webmobilefirst.com/en/) as well as with a real Iphone 10. 
Default mobile keyboard type is 'text'.
It could be better if it were 'number', or there were a configuration property to set.

**Comment by dipaksarkar** [comment]
We used text typed input field because we need to format as you type. Unfortunately number typed input will not accept text input. :)

**Comment by Germain-condo-group** [comment]
@dipaksarkar I'm also facing the same dilemma.

I have an idea that could solve this on library level, let me know what you think.

You could have two input:
- inputA: the regular one (text with formatting)
- inputB: a hidden one with `type='number'` that's positioned exactly over inputA (z-index: 10 or maybe relative positioning)

Then, on click focus would be on inputA, so it would show the number keyboard.

Then both input should be kept in sync with the model and voila!

**Comment by Germain-condo-group** [comment]
Only downside of this approach might be cursor would not work I guess, because it would be in invisible field so you couldn't really edit the middle of a number for example.

**Comment by Germain-condo-group** [comment]
Actually after extended research I found an even better solution @dipaksarkar 
https://css-tricks.com/everything-you-ever-wanted-to-know-about-inputmode/

This would be super easy and clean to integrate, what do you think?

**Comment by dipaksarkar** [comment]
@Germain-condo-group Thanks for your research. Can you please try this from your end. If you want me to try will take sometime. I'm really busy at the moment.
