### ISSUE TITLE
Dependency on vue-number-format?

### ISSUE THREAD

**Issue by eugenevk** [coders-tm/vue-number-format#4]
When installing the package I get the notification I need to install vue-number-format as well. Is this by design? Is that package needed as well?

**Comment by Rifaldikn** [comment]
> When installing the package I get the notification I need to install vue-number-format as well. Is this by design? Is that package needed as well?

Same issue with me but i change it to import number from '@coders-tm/vue-number-format' , but still no functionality

**Comment by dipaksarkar** [comment]
> When installing the package I get the notification I need to install vue-number-format as well. Is this by design? Is that package needed as well?

I didn't think so. It's a zero dependency package.
