### ISSUE TITLE
I cant disable negative in v2

### ISSUE THREAD

**Issue by thelittlelows** [coders-tm/vue-number-format#40]
Negative value is not limited by `min: 0` property
https://codesandbox.io/s/vue-2-playground-forked-ycf0i4?file=/src/App.vue

**Comment by thelittlelows** [comment]
https://github.com/coders-tm/vue-number-format/issues/35

**Comment by dipaksarkar** [comment]
@thelittlelows Please use 2.7.0
https://codesandbox.io/s/vue-2-playground-forked-j81v6q?file=/package.json

**Comment by kubyshkin1994** [comment]
@dipaksarkar you can paste text with a minus sign
