### ISSUE TITLE
You can paste text with a minus sign when using min: 0  v2.7.0

### ISSUE THREAD

**Issue by kubyshkin1994** [coders-tm/vue-number-format#41]
You can paste text with a minus sign when using `min: 0`
https://codesandbox.io/s/vue-2-playground-forked-j81v6q?file=/package.json

**Comment by kubyshkin1994** [comment]
https://github.com/coders-tm/vue-number-format/issues/40

**Comment by dipaksarkar** [comment]
Please check latest version v2.9.0
https://codesandbox.io/s/vue-2-playground-forked-rg59vy?file=/src/App.vue
