### ISSUE TITLE
Can't remove minus sign v2.7.0

### ISSUE THREAD

**Issue by kubyshkin1994** [coders-tm/vue-number-format#42]
You cannot remove the minus sign after it has been entered. The minus is erased when you lose focus from the field or select it and overwrite it with a number. https://recordit.co/8NwrBbTimf
https://codesandbox.io/s/vue-2-playground-forked-6hiufk?file=/src/App.vue

**Comment by dipaksarkar** [comment]
Please check latest version v2.9.0 
https://codesandbox.io/s/vue-2-playground-forked-rg59vy?file=/src/App.vue
