### ISSUE TITLE
Enabling reverse fill results in an input value when no value has been set by user

### ISSUE THREAD

**Issue by matty-liu** [coders-tm/vue-number-format#45]
Hello!

I am using: @coders-tm/vue-number-format: version "2.9.0" and I am running into a situation when using reverse fill, it auto populates the input with the value 0.00 (using the default settings). 
```
{
  "reverseFill": true
}
```
In my form, I have an optional input that is not required, so when the user submits, we receive the value "0.00" for that optional input rather than having no value being sent.

I am able to recreate this in the playground by clearing out all the values and then clicking the reverse fill option.

<img width="624" alt="Screen Shot 2023-03-31 at 2 26 04 PM" src="https://user-images.githubusercontent.com/24593321/229203726-c6911f0c-5cbc-463a-8278-6e166a7b2e95.png">

Could we update the default where if the input has not been touched and has no value, we just display the placeholder?

Once the input receives focus, that is when we would display the pre-populated input (0.00). If the user doesn't enter anything, and the input loses focus, the input remains empty and not take on the value. But if the user does input a value is when we would save the input value.

Cheers!

Matthew

**Comment by dipaksarkar** [comment]
Please try latest version v2.13.0 for Vue2.0. It will solved the issue. We can't use placeholder, but emitted empty value when value is

**Comment by matty-liu** [comment]
Thank you, I am now only seeing the value (0.00 for my example) when a user focuses on the input.

I'm wondering what UX is bet for the reverseFill feature.

Once we click into the input, it enforces the 0.00 value which is helpful for reverseFill (when user starts typing, they can see it starts at the smallest decimal place). If my user clicks out of the input and doesn't update it, the 0.00 is still applied (which I am okay with).

Is it reasonable if we allowed the user to clear the input when reverseFill is active to an empty string / null value? Currently we are unable to remove the 0.00 value. So backspacing while the input is 0.00 results in 0.00 rather than an empty string or null.

Cheers!
