### ISSUE TITLE
Unable to start a decimal input with a "."

### ISSUE THREAD

**Issue by matty-liu** [coders-tm/vue-number-format#46]
Hello!

I am using `@coders-tm/vue-number-format: "2.13.0"`

When inputting a decimal value, I am unable to start the input with the decimal separator, in my case it would be `.`.

As a user, if I typed `.9` I would expect the value `0.9`, but I end up with a value of `9` in the input.

In order to enter a value of `0.9`, a user would have to type `0.9` but in my personal opinion, typing `.9` should result in a value of `0.9`. Pasting the value of `.9` does result in the expected value of `0.9`.

Cheers!

**Comment by dipaksarkar** [comment]
Please check latest version

**Comment by dipaksarkar** [comment]
I have published version 2.15.0 for Vue 2
