### ISSUE TITLE
It allows "e", "s" letters when adding decimal option

### ISSUE THREAD

**Issue by lexar19** [coders-tm/vue-number-format#48]
I use v2.18.0. It allows me to input "e" and "s" letters when decimal option either true/false is added.
https://codesandbox.io/s/coders-tm-vue-number-format-2-forked-ptmmbh?file=/src/components/DirectiveBased.vue
![image](https://user-images.githubusercontent.com/30932969/231381465-845da3c0-973c-4cb5-8f32-b5317f2d3a00.png)

**Comment by dipaksarkar** [comment]
You are using wrong config. decimal only accept string value. i.e `,`

**Comment by lexar19** [comment]
Oh okay, but how to disable decimal?

**Comment by dipaksarkar** [comment]
use `precision: 0`

**Comment by lexar19** [comment]
It only works when you leave or unfocused the input. I use keyup function to get the inputs so every input will be recorded and the decimals are there. Hope you can able to prevent from actually inputting them just like the disable negative function.

**Comment by dipaksarkar** [comment]
Just now, I have released new version with the enhancement.
