### ISSUE TITLE
When Prefix is empty string convert separator in decimal

### ISSUE THREAD

**Issue by EmilioDifferding** [coders-tm/vue-number-format#49]
Hello first i have to thank you for the effort to bring to us this nice and easy to use component. I think there is a little bug when `prefix` is configured to an empty string 
I think The GIF can be more helpfull (attached)
Is there any thing to avoid this issue?
Thanks!!
![salida](https://user-images.githubusercontent.com/25306278/231576156-d635b6af-092b-4ede-ba92-4ef39c4de4e0.gif)

**Comment by dipaksarkar** [comment]
If you can check the seperator = . and decimal = , 
You have entered value after , for this reason after blur event it cleaned the value to 2 decimal places

**Comment by dipaksarkar** [comment]
Thank you for bringing the prefix configuration issue to my attention. It has been resolved in the latest version, which now allows for an empty string prefix without any issues.
