### ISSUE TITLE
Component comma decimal disappears on blur

### ISSUE THREAD

**Issue by CodeCasterNL** [coders-tm/vue-number-format#51]
1. Go to https://vue-number-format.netlify.app/guide/play-ground.html
2. Leave it to the defaults:
   * Separator: `.`
   * Decimal: `,`
   * Prefix: `Rs.`
   * Precision: `2`
   * Masked: `false`
3. Select all text in the Component
4. Type: `1,23`
5. Tab out of the field

Expected result: the "Rs.1,23" remains
![image](https://user-images.githubusercontent.com/1726333/235949758-2ffa3255-b78c-4f41-93c8-9df0d982f1a8.png)

Actual result: the input becomes "Rs.123"
![image](https://user-images.githubusercontent.com/1726333/235949828-65dff54b-2548-4e69-bcf2-ed523dbf4ec8.png)

v3.27.0

**Comment by dipaksarkar** [comment]
Please use latest version.
