### ISSUE TITLE
@change not triggered with formatted values on Safari (all devices)

### ISSUE THREAD

**Issue by MattOndo** [coders-tm/vue-number-format#52]
I'm displaying numbers with a thousands separator (comma) in the input field, all works well in chrome, firefox, etc. However in Safari (mobile, desktop, and tablet) if the value is greater than 1000 neither @change nor @blur events are triggered when the field value changes or the focus leaves the input field. Only when the number is less than 1000 or unformatted will it trigger these events. 

Below is how I'm using it:

Input field used in the template:
```
<vue-number v-model="fieldData.fieldName.value" id="fieldName" name="fieldName" v-bind="fieldTypes.wholeNumber" @click="$event.target.select()" @input="updateField($event)" @change="validateField('fieldName')" autocomplete="off" data-lpignore="true"></vue-number><span class="suffix" @click="$event.target.previousSibling.select()">/mo</span>

```

Format config stored in data obj:
```
fieldTypes: {
  "wholeNumber": {
    "separator": ",",
    "precision": 0,
    "masked": false,
    "minimumFractionDigits": 0,
    "min": 0,
    "reverseFill": false,
  }
}
```

Validate field method:
```
validateField(field) {
  if (this.fieldData[field].value) {
    console.log(field, this.fieldData[field].value);   // does not log to console if value is greater than 1000
    this.fieldData[field].isValid = true;
    this.calculateCosts(field);
  } else {
    this.fieldData[field].isValid = false;
  }
}
```

I have even added a standard <input type="number"> field connected to the same events, functions, and data properties. When I do this, the standard number field works as expected, but the vue-number field does not, and will not trigger the @change or @blur events.

**Comment by MattOndo** [comment]
Update: The issue seems to be with "precision". When precision is set to 1 or more, and a decimal is provided in the input, everything works normally. I found this sandbox which replicates the issue exactly. 

In safari:
Enter any number less than 1000, it works correctly.
Enter any number greater than 1000, it does not update the outputs.
Enter any number greater than 1000, but with decimals (i.e. 1000.0, 20000.0) it works correctly.

It seems the decimal is required for this to function, and fails silently, even if precision is set to 0.

This is not the case in any other web browser! Any help is appreciated

**Comment by dipaksarkar** [comment]
Please check latest version. I have fix the issue.
