### ISSUE TITLE
Component not Updating Bound Value for Values Beyond Min/Max

### ISSUE THREAD

**Issue by rzfff** [coders-tm/vue-number-format#53]
Hello,

When I input a value that exceeds the specified maximum or minimum value, the displayed value correctly changes to the set maximum or minimum value, but the bound value remains unchanged.

This issue can also be reproduced in the playground.
https://vue-number-format.netlify.app/guide/play-ground.html#playground

Set Maximum value :
![image](https://github.com/coders-tm/vue-number-format/assets/32006368/dc0294ba-0df1-4730-834f-b3d720cbe4b2)

When the value I input is greater than Maximum :
(Component)
![image](https://github.com/coders-tm/vue-number-format/assets/32006368/5330dfbc-0e92-4470-afc6-0b5aaad26644)

vue-number-format version: ^3.30.0
Vue.js version: ^3.2.13

**Comment by dipaksarkar** [comment]
Please check latest version

**Comment by rzfff** [comment]
The issue is fixed in the latest version. Thank you!
