### ISSUE TITLE
Wrong value on blur if reverse fill

### ISSUE THREAD

**Issue by mvuk27** [coders-tm/vue-number-format#57]
1. Go to https://vue-number-format.netlify.app/guide/play-ground.html
2. Mark Reverse Fill
8. Select all text in the Component
9. Type: 1,00
10. Tab out of the field
11. Expected result: the "Rs.1,00" remains
14. Actual result: the input becomes "Rs.0,01"

v3.31.0

**Comment by dipaksarkar** [comment]
Please check latest version
