### ISSUE TITLE
Prefix / suffix not working correctly if numbers or special characters used

### ISSUE THREAD

**Issue by Dakri** [coders-tm/vue-number-format#58]
Using `<VueNumberFormat v-model="testVal"
          v-bind="{ precision: 3, prefix: '1$=', suffix: '', decimal: ',', separator: '.' }">
        </VueNumberFormat>`

Results in the outcome to be unpredictable calculated value because the 1 in the prefix gets parsed to a number
also trying to add for example prefix :'+49-' results in a regex issue:
SyntaxError: Invalid regular expression: /+49-|/g: Nothing to repeat (at index.mjs:6:636)

i would suggest to simply escape the string before regexing it.

**Comment by dipaksarkar** [comment]
This component only for number  and currency format, you can't use number as prefix

**Comment by Dakri** [comment]
Obviously you did not read my Issue.
The problem is not only the numbers but it also do not work with special characters like "$ ^ .*" and more since you do not escape prefix and suffix in your code.

`    this.preSurRegExp = new RegExp(`${prefix}|${suffix}`, 'g')`

Right now, I am not able to do any contributions here, except this comments.  Please consider at least escaping the strings before using it in regex. I am also sure it should also be possible to use numbers in prefix and suffix if they are correctly removed by escaped prefix / suffix regex from component value before parseFloat it.

**Comment by dipaksarkar** [comment]
Please check latest version

**Comment by sysGenDP** [comment]
Hey thanks, that saves me a lot of trouble!
