### ISSUE TITLE
 Issue with Automatic Decimal Formatting in Directive

### ISSUE THREAD

**Issue by JoshuaHavilandCurtis** [coders-tm/vue-number-format#65]
Hi everyone,

I've successfully implemented the directive, and everything seems to be functioning as expected. However, I've noticed a small issue where automatic formatting is applied only to the first separator. For instance, in the number 10,000.00, the directive correctly formats the 10,000 part, but the .00 is not applied until you click off. This behavior is consistent with the examples provided in your documentation.

**Comment by dipaksarkar** [comment]
It's a general behavior. use reverse fill for auto decimal. Thanks
