### ISSUE TITLE
directive does not work

### ISSUE THREAD

**Issue by fos7er** [coders-tm/vue-number-format#68]
If I change number in input with directive the model value becomes string.
![image_2024-02-16_23-12-51](https://github.com/coders-tm/vue-number-format/assets/28354688/9a3783f3-ae0a-4c75-bdcc-fb88e535a1dc)

**Comment by dipaksarkar** [comment]
Directive alway return masked value. [Masking doesn't work with directive](https://vue-number-format.netlify.app/guide/config.html#masked)
