### ISSUE TITLE
Issue with large numbers

### ISSUE THREAD

**Issue by yusufkaracaburun** [coders-tm/vue-number-format#69]
When you use large numbers, it doesn't format correct
My config
```
{
          decimal: ",",
          separator: ".",
          prefix: "",
          suffix: "",
          precision: 2,
          masked: false,
          reverseFill: false,
          minimumFractionDigits: 2
}
```

**Steps to reproduce**
1. Use the above config
2. Type in 123456789
It's also possible to reproduce this in your playground: https://vue-number-format.netlify.app/guide/play-ground.html

**Expected**
123.456.789,00

**Actual**
1,23
But when you use , as separator and . as decimal it works.

**Comment by yusufkaracaburun** [comment]
any updates on this?

**Comment by dipaksarkar** [comment]
Working Fine, trying on Google Chrome and Mac

![REC-2024121234721 PM](https://github.com/user-attachments/assets/27a1b3f9-0fd3-42e9-9b31-b89153bc23b1)

**Comment by yusufkaracaburun** [comment]
@dipaksarkar your config is wrong. You need to change separator and decimal. So separator should be . and decimal should be ,

**Comment by yusufkaracaburun** [comment]
@dipaksarkar can try with separator . and decimal ,

**Comment by dipaksarkar** [comment]
I already tried playground it's working fine with latest version.
