### ISSUE TITLE
How do I pass empty value or null?

### ISSUE THREAD

**Issue by vedmant** [coders-tm/vue-number-format#7]
In my vase number can be nullable, but this component always parses it to 0. Is there a way to actually show empty input with a placeholder instead?

**Comment by dipaksarkar** [comment]
Added  `nullValue: ''` to your component options

**Comment by taunoha** [comment]
I am curious to know whether it is a bug or not. But when I use min and/or max props and the initial value of the field is NULL, the input will use the min value instead.
