### ISSUE TITLE
TypeError: v(...).cleanup is not a function

### ISSUE THREAD

**Issue by vedmant** [coders-tm/vue-number-format#71]
TypeError: v(...).cleanup is not a function

It happens when navigating back to the page with the `vue-number-format` input, looks like this line https://github.com/coders-tm/vue-number-format/blob/a6006d3dcbd8007cea3440f7147f33af192232ff/src/directive.ts#L79 probably for some reason the element is not present and it doesn't check for the presence, which throws this error. I think makes sense to update like: ` core.getInputElement(el)?.cleanup?.()`

**Comment by dipaksarkar** [comment]
Use latest version, I have fix the issue.
