### ISSUE TITLE
Dependency not found after installing

### ISSUE THREAD

**Issue by IDTitanium** [coders-tm/vue-number-format#8]
I installed this on a Vue 2 project. And then imported it into the project as specified in the documentation.

```
import number from "vue-number-format";

// register directive v-number and component <number>
Vue.use(number, { precision: 4 });
```

I get `dependency not found: 'vue-number-format'`.

I installed the version 2.1.1 and 2.1.0.

I also attempted to import it as `import number from "@coders-tm/vue-number-format"`. There was no error, but the functionality did not work.

Am I missing something?

**Comment by dipaksarkar** [comment]
You have installed wrong version. Please install @coders-tm/vue-number-format@2.0.7 for vue 2
